# config.py
config = {
    'num_episodes': 10_000,
    'max_steps': 1000,
    'actor_lr': 3e-4,
    'critic_lr': 3e-4,
    'gamma': 0.995,
    'batch_size': 64,
    'hidden_dim': 256,
    'buffer_capacity': 10_000,
    'load_models': True,
    'num_nodes': 2,
    'gravity': 0.81,
    'friction_coefficient': 0.1,
    'max_action': 0.5,
    'exploration_noise': 0.10,
    'swing_up_exploration_noise': 0.05,
    'swing_up_exploration_amplitude': 0.45,
    'swing_up_exploration_period_min': 60,
    'swing_up_exploration_period_max': 120,
    'swing_up_capture_score_threshold': 0.75,
    'swing_up_capture_noise': 0.03,
    'policy_noise': 0.08,
    'noise_clip': 0.15,
    'policy_delay': 2,
    'polyak_tau': 0.005,
    'learning_starts': 1_000,
    'train_every_steps': 4,
    'updates_per_train': 1,
    'initial_angle_noise': 0.1122,
    'initial_velocity_noise': 0.04,
    'episode_mode_probabilities': {
        'down_to_up': 0.0,
        'capture_vertical': 1.0,
        'fold_to_up': 0.0,
        'up_to_fold': 0.0,
    },
    'adaptive_curriculum_enabled': False,
    'curriculum_start_episode': 300,
    'curriculum_window': 200,
    'curriculum_min_probabilities': {
        'down_to_up': 0.20,
        'capture_vertical': 0.20,
        'fold_to_up': 0.10,
        'up_to_fold': 0.05,
    },
    'curriculum_max_probabilities': {
        'down_to_up': 0.50,
        'capture_vertical': 0.45,
        'fold_to_up': 0.35,
        'up_to_fold': 0.20,
    },
    'transition_switch_step_min': 50,
    'transition_switch_step_max': 150,
    'transition_pre_switch_reward_weight': 0.20,
    'capture_angle_noise': 0.18,
    'capture_cart_velocity_noise': 0.05,
    'capture_angular_velocity_noise': 2.0,
    'down_angle_noise': 0.1122,
    'post_switch_reward_weight': 2.0,
    'transition_improvement_weight': 0.5,
    'post_switch_low_score_threshold': 0.2,
    'post_switch_low_score_penalty': 0.5,
    'swing_up_vertical_velocity_weight': 0.0,
    'swing_up_momentum_weight': 0.0,
    'swing_up_height_progress_weight': 3.0,
    'swing_up_score_progress_weight': 2.0,
    'swing_up_free_motion_score_threshold': 0.45,
    'swing_up_drive_score_threshold': 0.55,
    'swing_up_free_motion_action_penalty_scale': 0.0,
    'swing_up_free_motion_velocity_penalty_scale': 0.0,
    'swing_up_action_penalty_scale': 0.25,
    'swing_up_velocity_penalty_scale': 0.20,
    'capture_velocity_bonus_weight': 1.0,
    'capture_allowed_angular_speed': 1.5,
    'capture_target_speed_discount': 0.6,
    'capture_overspeed_penalty_weight': 0.35,
    'capture_height_penalty_weight': 0.9,
    'capture_lost_penalty_weight': 1.5,
    'capture_rest_penalty_weight': 0.6,
    'target_shaping_weight': 0.45,
    'target_entry_bonus': 1.0,
    'hold_progress_bonus': 4.0,
    'hold_required_steps': 120,
    'capture_hold_bonus': 0.0,
    'render_training': True,
    'render_every_episodes': 20,
    'render_first_episode': True,
    'debug': False,
    
    # Options de visualisation et de plots
    'plot_config': {
        'enable_plots': True,           # Activer/désactiver tous les graphiques
        'plot_frequency': 100,          # Fréquence de génération des graphiques principaux
        'full_plot_frequency': 1_000,    # Fréquence de génération des graphiques complets
        'max_points_per_plot': 1_000,    # Nombre maximal de points par graphique
        'plot_dpi': 100                 # Résolution des graphiques (DPI)
    }
}
